name: daily-cron
on:
  schedule:
    - cron: "*/2 * * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call apify
        run: |
          curl --request POST \
          --url 'https://how-many-two.vercel.app/api/cron' \
